import './globals.css'
import type { Metadata } from 'next'
import { Barlow } from 'next/font/google'
import Provider from './provider'
import { Toaster } from '@/components/ui/toaster'

const barlow = Barlow({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Ignite Call',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={barlow.className}>
        <Provider>{children}</Provider>
        <Toaster />
      </body>
    </html>
  )
}
